# Generated by Django 4.1.1 on 2022-10-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name': 'accounts', 'verbose_name_plural': 'accounts'},
        ),
    ]
