# Generated by Django 4.1.1 on 2022-10-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('category', '0002_alter_cateogory_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cateogory',
            new_name='Category',
        ),
    ]
